name: 🚀 Cypress Tests - Execução Paralela + Relatório + GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  exam1:
    name: 🧪 Exam 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm run run:exam1
      - uses: actions/upload-artifact@v4
        with:
          name: exam1-report
          path: cypress/reports

  exam2:
    name: 🧪 Exam 2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm run run:exam2
      - uses: actions/upload-artifact@v4
        with:
          name: exam2-report
          path: cypress/reports

  exam3:
    name: 🧪 Exam 3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm run run:exam3
      - uses: actions/upload-artifact@v4
        with:
          name: exam3-report
          path: cypress/reports

  merge-and-publish:
    name: 📊 Merge Reports & Deploy
    runs-on: ubuntu-latest
    needs: [exam1, exam2, exam3]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: cypress/reports

      - name: Merge reports and generate HTML
        run: |
          npm install -g mochawesome-merge mochawesome-report-generator
          npx mochawesome-merge cypress/reports/**/mochawesome*.json > mochawesome.json
          npx marge mochawesome.json --reportDir=public --inline

      - name: Set Git remote manually
        run: |
          git config --global user.name "anselmotadeu"
          git config --global user.email "anselmotadeu@users.noreply.github.com"
          git remote remove origin || true
          git remote add origin https://github.com/${{ github.repository }}.git

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          force_orphan: true
